name: R Package Validation Report
author: Roche
description: A Github Action that generates a validation report for an R package.

inputs:
  report_pkg_dir:
    description: Path to package's root.
    required: false
    default: "."
  report_template_path:
    description: |
      File path of the R markdown template to use for the report.
      The default template is available [here.](./template.qmd)
    required: false
    default: "./template.qmd"
  report_rmarkdown_format:
    description: |
      The file format of the validation report. See `rmarkdown::render`'s
      `output_format` parameter for accepted values.
    required: false
    default: "all"
  report_output_prefix:
    description: >
      The output filename prefix for the validation report. If left blank,
      it defaults to the following convention:
      `<package name>-<package version>-validation-report`.
    required: false
    default: ""
  no_cache:
    description: "Disable github action R dependency caching"
    required: false
    default: "false"
  cache_version:
    description: "Version of the cache. To clean cache bump this version."
    required: false
    default: "v1"
  disable_install_dev_deps:
    description: |
      Disable installation of dev dependencies while
      building the report.
    required: false
    default: "false"
outputs:
  report_output_filename:
    description: Filename of the generated report.
    value: ${{ steps.report-generator.outputs.output-filename }}
branding: # https://feathericons.com/
  icon: "award"
  color: "blue"

runs:
  using: "composite"
  steps:

    # - name: Cache R packages
    #   if: "contains(inputs.no_cache, 'false')"
    #   uses: actions/cache@v4
    #   with:
    #     path: /home/runner/work/_temp/Library
    #     key: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}-${{ hashFiles('DESCRIPTION') }}
    #     restore-keys: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}

    # - name: Cache Tex packages
    #   if: "contains(inputs.no_cache, 'false')"
    #   uses: actions/cache@v4
    #   with:
    #     path: /home/runner/work/_temp/TinyTeX
    #     key: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.texlive_version.outputs.TEX_LIVE_VERSION }}-${{ hashFiles(inputs.report_template_path) }}
    #     restore-keys: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.texlive_version.outputs.TEX_LIVE_VERSION }}

    - name: Install dependencies
      run: |
        ${GITHUB_ACTION_PATH}/dependencies.R
      shell: bash

    - name: Run report generator
      id: report-generator
      run: |
        ${GITHUB_ACTION_PATH}/report-generator.R
        #filename=$(basename $(cat /tmp/report_file_path.txt))
        #echo "output-filename=${filename}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        # Composite action doesn't set inputs as env vars.
        # We need to do this manually...
        INPUT_REPORT_PKG_DIR: ${{ inputs.report_pkg_dir }}
        INPUT_REPORT_TEMPLATE_PATH: ${{ inputs.report_template_path }}
        INPUT_REPORT_RMARKDOWN_FORMAT: ${{ inputs.report_rmarkdown_format }}
        INPUT_REPORT_OUTPUT_PREFIX: ${{ inputs.report_output_prefix }}
        DISABLE_INSTALL_DEV_DEPS: ${{ inputs.disable_install_dev_deps }}
