name: R Package Validation Report
author: Roche
description: A Github Action that generates a validation report for an R package.

inputs:
  report_pkg_dir:
    description: Path to package's root.
    required: false
    default: "."
  report_template_path:
    description: |
      File path of the R markdown template to use for the report.
      The default template is available [here.](./template.Rmd)
    required: false
    default: "template.Rmd"
  report_rmarkdown_format:
    description: |
      The file format of the validation report. See `rmarkdown::render`'s
      `output_format` parameter for accepted values.
    required: false
    default: "all"

# Run as a Docker action
runs:
  using: 'docker'
  image: './Dockerfile'

branding: # https://feathericons.com/
  icon: 'award'
  color: 'blue'
