---
name: Test This Action

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.package.name }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        package:
          - name: aragog
            report_pkg_dir: ./tests/packages/aragog
            report_template_path: ./template.Rmd
            report_rmarkdown_format: pdf_document
          - name: buckbeak
            report_pkg_dir: ./tests/packages/buckbeak
            report_template_path: ./tests/packages/buckbeak/validation-template.Rmd
            report_rmarkdown_format: html_document


    steps:
      - name: Checkout ${{ matrix.package.name }}
        uses: actions/checkout@v2

      - name: Generate validation report for ${{ matrix.package.name }}
        uses: ./
        with:
          report_pkg_dir: ${{ matrix.package.report_pkg_dir }}
          report_template_path: ${{ matrix.package.report_template_path }}
          report_rmarkdown_format: ${{ matrix.package.report_rmarkdown_format }}

      - name: Upload ${{ matrix.package.name }} validation report
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: ${{ matrix.package.name }} validation report
          path: validation_report.*
          if-no-files-found: error
